import { Btn } from '@/contracts';
import { makeMatch, skipIntro, run, ManualSource } from '@/combat/testing/harness';
const m = makeMatch();
const a = new ManualSource();
const b = new ManualSource();
m.setSources(a, b);
skipIntro(m);
console.log('live at tick', m.tick, 'phase', m.phase);
const f0 = m.fighters[0], f1 = m.fighters[1];
console.log('start', f0.view.x, f0.view.state, f1.view.x, f1.view.state, 'bounds0', f0.view.boundsX0, f0.view.boundsX1, f0.view.boundsY0, f0.view.boundsY1);
a.moveX = 1;
run(m, 60);
console.log('after walking 1s', f0.view.x.toFixed(1), f0.view.vx.toFixed(1), f0.view.state);
a.moveX = 0;
run(m, 60);
console.log('after glide', f0.view.x.toFixed(1), f0.view.vx.toFixed(1), f0.view.state, 'dist', (f1.view.x - f0.view.x).toFixed(1));
a.held = Btn.STRIKE;
m.step();
console.log('press strike: state', f0.view.state, f0.view.moveId, f0.view.phase, f0.view.moveTick);
a.held = 0;
for (let i = 0; i < 45; i++) { m.step(); const hits = m.events.filter(e => e.t === 'hit'); if (hits.length) console.log('tick', i, 'hit', JSON.stringify(hits[0]).slice(0,200)); }
console.log('foe mass frac', f1.view.bodyStats.massFrac.toFixed(3), 'state', f1.view.state, 'meter', f0.view.meter.toFixed(3), f1.view.meter.toFixed(3));
