/**
 * Autotune: an unattended loop that moves every titan's two global balance knobs (`balance.power`, `balance.durability` in its JSON)
 * toward a 50 % overall win rate. Each iteration plays a small all-pairs tournament on the REAL matter world with the balance tournament's
 * worker pool, computes each titan's overall rate, and steps log(power) down / log(durability) up by a damped share of the excess.
 *
 *   npm run autotune -- [--n=24] [--level=3] [--seed=9000] [--iters=12] [--workers=4] [--titans=a,b,...] [--gain=1.6] [--damp=0.8]
 *                       [--tol=0.05] [--min=0.5] [--max=2] [--fresh] [--dry] [--no-docs]
 *
 *  - fights per pair use seeds `seed + iter*n + k`, sides alternated, the same seeds for every pair in an iteration;
 *  - the loop stops when every titan is within `tol` of 50 % in two consecutive iterations, or after `iters` iterations;
 *  - after every iteration the knobs are written back into the JSON files (only the `balance` block) and the state is saved to
 *    .scratch/autotune/state.json, so a killed run resumes where it stopped (`--fresh` starts over from the JSON values);
 *  - the history is written to docs/BALANCE.md between the autotune markers (unless --no-docs).
 */
import { existsSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { availableParallelism } from 'node:os';
import type { Difficulty, TitanId } from '@/contracts';
import { runPool, type Job, type Result } from './balance';

type Knobs = { power: number; durability: number };

interface Step {
  iter: number;
  seedBase: number;
  fights: number;
  rates: Record<string, number>;
  knobs: Record<string, Knobs>;
  worst: { pair: string; rate: number }[];
  maxDev: number;
  failed: number;
}

interface State {
  level: number;
  titans: TitanId[];
  knobs: Record<string, Knobs>;
  history: Step[];
  calm: number;
}

const args = process.argv.slice(2);
const opt = (k: string, d: string): string =>
  (args.find((a) => a.startsWith(`--${k}=`)) ?? `--${k}=${d}`).split('=').slice(1).join('=');
const flag = (k: string): boolean => args.includes(`--${k}`);
const clampK = (x: number, lo: number, hi: number): number => Math.min(hi, Math.max(lo, x));
const BEGIN = '<!-- autotune:begin (generated by tools/ai/autotune.ts; do not edit by hand) -->';
const END = '<!-- autotune:end -->';

async function writeKnobs(id: string, k: Knobs): Promise<void> {
  const path = `src/titans/${id}.json`;
  const d = JSON.parse(readFileSync(path, 'utf8')) as Record<string, unknown>;
  d['balance'] = { power: +k.power.toFixed(3), durability: +k.durability.toFixed(3) };
  const prettier = await import('prettier');
  writeFileSync(path, await prettier.format(JSON.stringify(d), { parser: 'json' }));
}

async function writeDocs(state: State): Promise<void> {
  const path = 'docs/BALANCE.md';
  let text = readFileSync(path, 'utf8');
  const L: string[] = [BEGIN, '', '## Autotune (generated)', ''];
  L.push(
    `Level ${state.level}, titans ${state.titans.join(', ')}. Each row is one iteration of \`npm run autotune\`: overall win rate of every titan ` +
      `over an all-pairs tournament, then the knobs it ended with (power / durability). Rates are noisy (one standard error is about ` +
      `${state.history.length ? ((100 * 0.5) / Math.sqrt(Math.max(1, (state.history[state.history.length - 1]!.fights * 2) / state.titans.length))).toFixed(0) : '?'} points).`,
    '',
  );
  L.push(`| iter | ${state.titans.join(' | ')} | max dev | worst pair |`);
  L.push(`|---|${state.titans.map(() => '---:').join('|')}|---:|---|`);
  for (const h of state.history) {
    L.push(
      `| ${h.iter} | ${state.titans.map((t) => `${(100 * (h.rates[t] ?? 0)).toFixed(0)}%`).join(' | ')} | ${(100 * h.maxDev).toFixed(0)} | ${h.worst[0] ? `${h.worst[0].pair} ${(100 * h.worst[0].rate).toFixed(0)}%` : ''} |`,
    );
  }
  L.push('', '| titan | power | durability |', '|---|---:|---:|');
  for (const t of state.titans)
    L.push(`| ${t} | ${state.knobs[t]!.power.toFixed(3)} | ${state.knobs[t]!.durability.toFixed(3)} |`);
  L.push('', END);
  const section = L.join('\n');
  const i = text.indexOf('<!-- autotune:begin');
  const j = text.indexOf(END);
  if (i >= 0 && j > i) text = text.slice(0, i) + section + text.slice(j + END.length);
  else text = text.replace(/\s*$/, '\n\n') + section + '\n';
  writeFileSync(path, text);
}

async function main(): Promise<void> {
  const { IMPLEMENTED_TITANS, getTitanDef } = await import('@/titans');
  const level = +opt('level', '3') as Difficulty;
  const n = +opt('n', '24');
  const seed0 = +opt('seed', '9000');
  const iters = +opt('iters', '12');
  const workers = Math.max(1, +opt('workers', String(Math.min(4, availableParallelism()))));
  const gain = +opt('gain', '1.6');
  const damp = +opt('damp', '0.8');
  const tol = +opt('tol', '0.05');
  const lo = +opt('min', '0.5');
  const hi = +opt('max', '2');
  const titans = (opt('titans', '') ? opt('titans', '').split(',') : [...IMPLEMENTED_TITANS]) as TitanId[];
  mkdirSync('.scratch/autotune', { recursive: true });
  const statePath = '.scratch/autotune/state.json';
  let state: State | null = null;
  if (!flag('fresh') && existsSync(statePath)) {
    try {
      state = JSON.parse(readFileSync(statePath, 'utf8')) as State;
      if (state.titans.join() !== titans.join() || state.level !== level) state = null;
    } catch {
      state = null;
    }
  }
  if (!state) {
    const knobs: Record<string, Knobs> = {};
    for (const t of titans) {
      const b = (getTitanDef(t) as unknown as { balance?: Partial<Knobs> }).balance ?? {};
      knobs[t] = { power: b.power ?? 1, durability: b.durability ?? 1 };
    }
    state = { level, titans, knobs, history: [], calm: 0 };
  }
  const pairs: [TitanId, TitanId][] = [];
  for (let i = 0; i < titans.length; i++)
    for (let j = i + 1; j < titans.length; j++) pairs.push([titans[i]!, titans[j]!]);

  while (state.history.length < iters && state.calm < 2) {
    const iter = state.history.length + 1;
    const seedBase = seed0 + (iter - 1) * n;
    const queue: Job[] = [];
    for (let k = 0; k < n; k++)
      for (const [a, b] of pairs)
        queue.push({
          key: `${a}|${b}|L${level}v${level}|${seedBase + k}`,
          a,
          b,
          la: level,
          lb: level,
          seed: seedBase + k,
          swapped: k % 2 === 1,
          index: k,
          knobs: state.knobs,
        });
    const results: Result[] = [];
    const t0 = performance.now();
    console.log(
      `autotune iteration ${iter}: ${queue.length} fights (${pairs.length} pairs x ${n}), knobs ` +
        titans
          .map((t) => `${t} ${state!.knobs[t]!.power.toFixed(2)}/${state!.knobs[t]!.durability.toFixed(2)}`)
          .join(', '),
    );
    await runPool(queue, workers, 240_000, (r) => results.push(r));
    // overall rates and per-pair rates
    const score: Record<string, number> = {};
    const games: Record<string, number> = {};
    const pairScore = new Map<string, { w: number; n: number }>();
    for (const t of titans) {
      score[t] = 0;
      games[t] = 0;
    }
    for (const r of results) {
      const va = r.winner === 'a' ? 1 : r.winner === 'draw' ? 0.5 : 0;
      score[r.a]! += va;
      score[r.b]! += 1 - va;
      games[r.a]!++;
      games[r.b]!++;
      const key = `${r.a} v ${r.b}`;
      const p = pairScore.get(key) ?? { w: 0, n: 0 };
      p.w += va;
      p.n++;
      pairScore.set(key, p);
    }
    const rates: Record<string, number> = {};
    for (const t of titans) rates[t] = games[t]! ? score[t]! / games[t]! : 0.5;
    const worst = [...pairScore.entries()]
      .map(([pair, p]) => ({ pair, rate: p.w / p.n }))
      .sort((x, y) => Math.abs(y.rate - 0.5) - Math.abs(x.rate - 0.5))
      .slice(0, 4);
    const maxDev = Math.max(...titans.map((t) => Math.abs(rates[t]! - 0.5)));
    const failed = results.filter((r) => r.error).length;
    console.log(
      `  rates ${titans.map((t) => `${t} ${(100 * rates[t]!).toFixed(0)}%`).join(', ')}; max deviation ${(100 * maxDev).toFixed(0)} points; ` +
        `${((performance.now() - t0) / 60000).toFixed(1)} min, ${failed} failed`,
    );
    console.log(`  worst pairs: ${worst.map((w) => `${w.pair} ${(100 * w.rate).toFixed(0)}%`).join('; ')}`);
    state.history.push({
      iter,
      seedBase,
      fights: results.length,
      rates,
      knobs: JSON.parse(JSON.stringify(state.knobs)) as Record<string, Knobs>,
      worst,
      maxDev,
      failed,
    });
    state.calm = maxDev <= tol ? state.calm + 1 : 0;
    if (state.calm >= 2) {
      console.log(
        '  converged: every titan within the tolerance in two consecutive iterations (knobs kept as they were measured)',
      );
    } else {
      // step: the excess splits between the two knobs; the step shrinks each iteration
      const step = gain * Math.pow(damp, iter - 1);
      for (const t of titans) {
        const d = clampK(step * (rates[t]! - 0.5), -0.5, 0.5); // in ln units, total strength change
        const k = state.knobs[t]!;
        k.power = clampK(k.power * Math.exp(-d / 2), lo, hi);
        k.durability = clampK(k.durability * Math.exp(d / 2), lo, hi);
      }
    }
    writeFileSync(statePath, JSON.stringify(state));
    if (!flag('dry')) for (const t of titans) await writeKnobs(t, state.knobs[t]!);
    if (!flag('no-docs')) await writeDocs(state);
  }
  console.log(
    `autotune: ${state.calm >= 2 ? 'converged' : 'stopped'} after ${state.history.length} iterations. knobs: ` +
      titans
        .map((t) => `${t} ${state!.knobs[t]!.power.toFixed(3)}/${state!.knobs[t]!.durability.toFixed(3)}`)
        .join(', '),
  );
}

void main().then(() => process.exit(0));
