/**
 * Balance tournament: every pair of implemented titans (plus mirrors) at equal AI level, headless, on the REAL matter world,
 * fanned out over worker_threads. Seeded, resumable, robust to a crashing or stalling fight (counted as a draw and logged).
 *
 *   npm run balance -- --ladder [--levels=6v1,6v3,3v1,5v3] [--n=50]   (mirror matches per titan and level pair; monotonicity table)
 *   npm run balance -- [--n=100] [--level=3] [--la=3 --lb=3] [--seed=1000] [--workers=4] [--titans=lastone,asteroid,...]
 *                      [--no-mirror] [--timeout=240] [--fresh] [--no-docs] [--report]
 *
 *  - fight i of a pair uses seed `seed + i` for every pair (differences are not seed noise) and alternates which titan is on the left;
 *  - jobs are interleaved (fight 0 of every pair, then fight 1, ...), so an interrupted run has an even sample everywhere;
 *  - partial results live in .scratch/balance/results-<key>.json and are reloaded on the next run (resume); `--fresh` discards them;
 *  - `--report` only rewrites the outputs from the stored results (no fights);
 *  - outputs: the generated section of docs/BALANCE.md (between the balance markers) and docs/balance-results.json.
 */
import { existsSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { availableParallelism } from 'node:os';
import { Worker, isMainThread, parentPort, workerData } from 'node:worker_threads';
import { fileURLToPath } from 'node:url';
import type { Difficulty, TitanId } from '@/contracts';
import type { playMatch as import_playMatch } from './duel';

type PlayMatch = typeof import_playMatch;

interface Job {
  key: string;
  a: TitanId;
  b: TitanId;
  la: Difficulty;
  lb: Difficulty;
  seed: number;
  swapped: boolean;
  index: number;
}

interface Result {
  key: string;
  a: TitanId;
  b: TitanId;
  index: number;
  swapped: boolean;
  /** 'a' / 'b' by titan (for mirrors: 'a' = the fighter on the left), 'draw' for an undecided or failed fight. */
  winner: 'a' | 'b' | 'draw';
  /** Round wins by titan. */
  roundsA: number;
  roundsB: number;
  rounds: number[];
  timeouts: number;
  ticks: number;
  error?: string;
  wallMs: number;
}

const SELF = fileURLToPath(import.meta.url);

/* ------------------------------------------------------------------------------------------------ *
 *  worker: plays fights one at a time
 * ------------------------------------------------------------------------------------------------ */
async function workerMain(): Promise<void> {
  // tsconfig `paths` (the `@/` alias) are not inherited by worker threads: register them here before anything imports the sim
  const { register } = await import('tsx/esm/api');
  register({ tsconfig: 'tsconfig.json' });
  const duelPath = './duel.ts';
  const { playMatch } = (await import(duelPath)) as { playMatch: PlayMatch };
  const port = parentPort!;
  port.on('message', (job: Job) => {
    const t0 = performance.now();
    let out: Result;
    try {
      const ta = job.swapped ? job.b : job.a;
      const tb = job.swapped ? job.a : job.b;
      const l1 = job.swapped ? job.lb : job.la;
      const l2 = job.swapped ? job.la : job.lb;
      const { res } = playMatch(job.seed, ta, tb, l1, l2, '', false);
      const slotOfA = job.swapped ? 1 : 0;
      const winner: Result['winner'] = res.winner === -1 ? 'draw' : res.winner === slotOfA ? 'a' : 'b';
      out = {
        key: job.key,
        a: job.a,
        b: job.b,
        index: job.index,
        swapped: job.swapped,
        winner: res.reason === 'tick cap' ? 'draw' : winner,
        roundsA: res.wins[slotOfA]!,
        roundsB: res.wins[1 - slotOfA]!,
        rounds: res.rounds.map((r) => r.ticks),
        timeouts: res.rounds.filter((r) => r.timeout).length,
        ticks: res.ticks,
        error: res.reason === 'tick cap' ? 'tick cap' : undefined,
        wallMs: performance.now() - t0,
      };
    } catch (e) {
      out = {
        key: job.key,
        a: job.a,
        b: job.b,
        index: job.index,
        swapped: job.swapped,
        winner: 'draw',
        roundsA: 0,
        roundsB: 0,
        rounds: [],
        timeouts: 0,
        ticks: 0,
        error: `crash: ${e instanceof Error ? e.message : String(e)}`,
        wallMs: performance.now() - t0,
      };
    }
    port.postMessage(out);
  });
  port.postMessage({ ready: true });
}

/* ------------------------------------------------------------------------------------------------ *
 *  reporting
 * ------------------------------------------------------------------------------------------------ */
const BEGIN = '<!-- balance:begin (generated by tools/ai/balance.ts; do not edit by hand) -->';
const END = '<!-- balance:end -->';

interface Cell {
  n: number;
  winsA: number;
  winsB: number;
  draws: number;
  /** a's win share counting a draw as half. */
  rate: number;
  se: number;
  /** a's win share when a started on the left / on the right. */
  left: number;
  right: number;
  roundMean: number;
  round1Mean: number;
  timeouts: number;
  errors: number;
}

function summarise(rs: Result[]): Cell {
  const n = rs.length;
  const winsA = rs.filter((r) => r.winner === 'a').length;
  const winsB = rs.filter((r) => r.winner === 'b').length;
  const draws = n - winsA - winsB;
  const rate = n ? (winsA + 0.5 * draws) / n : 0;
  const share = (xs: Result[]): number =>
    xs.length ? xs.filter((r) => r.winner === 'a').length / xs.length : 0;
  const all = rs.flatMap((r) => r.rounds);
  const first = rs.map((r) => r.rounds[0]).filter((x): x is number => x !== undefined);
  const mean = (xs: number[]): number => (xs.length ? xs.reduce((x, y) => x + y, 0) / xs.length / 60 : 0);
  return {
    n,
    winsA,
    winsB,
    draws,
    rate,
    se: n ? Math.sqrt((rate * (1 - rate)) / n) : 0,
    left: share(rs.filter((r) => !r.swapped)),
    right: share(rs.filter((r) => r.swapped)),
    roundMean: mean(all),
    round1Mean: mean(first),
    timeouts: rs.reduce((s, r) => s + r.timeouts, 0),
    errors: rs.filter((r) => r.error).length,
  };
}

function pct(x: number): string {
  return `${(x * 100).toFixed(0)}%`;
}

function render(
  titans: TitanId[],
  results: Result[],
  la: number,
  lb: number,
  seed: number,
  nTarget: number,
): string {
  const by = new Map<string, Result[]>();
  for (const r of results) {
    const k = `${r.a}|${r.b}`;
    if (!by.has(k)) by.set(k, []);
    by.get(k)!.push(r);
  }
  const cell = (a: TitanId, b: TitanId): Cell | null => {
    const direct = by.get(`${a}|${b}`);
    if (direct) return summarise(direct);
    const rev = by.get(`${b}|${a}`);
    if (!rev) return null;
    // flip the perspective of a stored (b|a) pair
    return summarise(
      rev.map((r) => ({
        ...r,
        winner: r.winner === 'a' ? 'b' : r.winner === 'b' ? 'a' : 'draw',
        swapped: !r.swapped,
      })),
    );
  };
  const L: string[] = [];
  L.push(BEGIN, '');
  L.push(`## Tournament (generated)`);
  L.push('');
  L.push(
    `Level ${la}${la === lb ? '' : ` v ${lb}`}, seed base ${seed}, target ${nTarget} fights per pair, real matter world, sides alternated. ` +
      `Cells are the ROW titan's win rate against the COLUMN titan (a draw counts half); ± is one standard error. ` +
      `A cell outside 35–65 % is marked with an asterisk. Mirrors read the share won by the titan that started on the left.`,
  );
  L.push('');
  L.push(`| row v col | ${titans.join(' | ')} |`);
  L.push(`|---|${titans.map(() => '---:').join('|')}|`);
  for (const a of titans) {
    const cols = titans.map((b) => {
      const c = cell(a, b);
      if (!c || c.n === 0) return '—';
      const flag = a !== b && (c.rate < 0.35 || c.rate > 0.65) ? '*' : '';
      return `${pct(c.rate)}${flag} ±${pct(c.se)} (${c.n})`;
    });
    L.push(`| **${a}** | ${cols.join(' | ')} |`);
  }
  L.push('');
  L.push('### Per titan (non-mirror fights)');
  L.push('');
  L.push('| titan | fights | win rate | wins–losses–draws | mean round | round 1 |');
  L.push('|---|---:|---:|---:|---:|---:|');
  for (const a of titans) {
    let w = 0;
    let l = 0;
    let d = 0;
    let rounds = 0;
    let roundSum = 0;
    let first = 0;
    let firstN = 0;
    for (const b of titans) {
      if (a === b) continue;
      const rs = by.get(`${a}|${b}`) ?? [];
      const rv = by.get(`${b}|${a}`) ?? [];
      for (const r of rs) {
        if (r.winner === 'a') w++;
        else if (r.winner === 'b') l++;
        else d++;
      }
      for (const r of rv) {
        if (r.winner === 'b') w++;
        else if (r.winner === 'a') l++;
        else d++;
      }
      for (const r of [...rs, ...rv]) {
        rounds += r.rounds.length;
        roundSum += r.rounds.reduce((x, y) => x + y, 0);
        if (r.rounds[0] !== undefined) {
          first += r.rounds[0];
          firstN++;
        }
      }
    }
    const n = w + l + d;
    L.push(
      `| ${a} | ${n} | ${n ? pct((w + 0.5 * d) / n) : '—'} | ${w}–${l}–${d} | ${rounds ? (roundSum / rounds / 60).toFixed(1) : '—'} s | ${firstN ? (first / firstN / 60).toFixed(1) : '—'} s |`,
    );
  }
  L.push('');
  L.push('### Per pair');
  L.push('');
  L.push(
    '| pair | fights | wins a–b–draws | a rate | a on left | a on right | mean round | round 1 | clock ends | failed |',
  );
  L.push('|---|---:|---:|---:|---:|---:|---:|---:|---:|---:|');
  for (let i = 0; i < titans.length; i++)
    for (let j = i; j < titans.length; j++) {
      const a = titans[i]!;
      const b = titans[j]!;
      const c = cell(a, b);
      if (!c || c.n === 0) continue;
      L.push(
        `| ${a} v ${b} | ${c.n} | ${c.winsA}–${c.winsB}–${c.draws} | ${pct(c.rate)} | ${pct(c.left)} | ${pct(c.right)} | ${c.roundMean.toFixed(1)} s | ${c.round1Mean.toFixed(1)} s | ${c.timeouts} | ${c.errors} |`,
      );
    }
  L.push('', END);
  return L.join('\n');
}

function renderLadder(
  specs: { a: TitanId; la: number; lb: number }[],
  results: Result[],
  seed: number,
  nTarget: number,
): string {
  const by = new Map<string, Result[]>();
  for (const r of results) {
    const k = `${r.a}|${r.key.split('|')[2]}`;
    if (!by.has(k)) by.set(k, []);
    by.get(k)!.push(r);
  }
  const titans = [...new Set(specs.map((x) => x.a))];
  const levels = [...new Set(specs.map((x) => `${x.la}v${x.lb}`))];
  const L: string[] = [];
  L.push(
    '<!-- balance-ladder:begin (generated by tools/ai/balance.ts --ladder; do not edit by hand) -->',
    '',
  );
  L.push('## AI ladder (generated)', '');
  L.push(
    `Mirror matches, real matter world, seed base ${seed}, target ${nTarget} fights per cell, sides alternated. ` +
      `Cells are the win rate of the HIGHER level (a draw counts half) with one standard error. ` +
      `Targets: 6v1 at least 70 %, and every adjacent-level cell above 50 %. * marks a cell at or below 50 %.`,
    '',
  );
  L.push(`| titan | ${levels.map((l) => l.replace('v', ' v ')).join(' | ')} | monotone |`);
  L.push(`|---|${levels.map(() => '---:').join('|')}|---|`);
  const rateOf = (t: TitanId, lv: string): number | null => {
    const rs = by.get(`${t}|L${lv}`);
    return rs && rs.length ? summarise(rs).rate : null;
  };
  for (const t of titans) {
    const cols = levels.map((lv) => {
      const rs = by.get(`${t}|L${lv}`);
      if (!rs || rs.length === 0) return '—';
      const c = summarise(rs);
      return `${pct(c.rate)}${c.rate <= 0.5 ? '*' : ''} ±${pct(c.se)} (${c.n})`;
    });
    const r61 = rateOf(t, '6v1');
    const r63 = rateOf(t, '6v3');
    const r31 = rateOf(t, '3v1');
    const r53 = rateOf(t, '5v3');
    const parts: boolean[] = [];
    if (r61 !== null) parts.push(r61 >= 0.7);
    for (const r of [r63, r31, r53]) if (r !== null) parts.push(r > 0.5);
    if (r61 !== null && r63 !== null && r31 !== null) parts.push(r61 >= Math.max(r63, r31) - 0.05);
    L.push(
      `| ${t} | ${cols.join(' | ')} | ${parts.length === 0 ? '—' : parts.every(Boolean) ? 'yes' : 'NO'} |`,
    );
  }
  L.push('', '<!-- balance-ladder:end -->');
  return L.join('\n');
}

async function writeDocs(
  section: string,
  jsonOut: unknown,
  tag = 'balance',
  jsonPath = 'docs/balance-results.json',
): Promise<void> {
  const path = 'docs/BALANCE.md';
  let text = existsSync(path) ? readFileSync(path, 'utf8') : '# Balance\n';
  const end = `<!-- ${tag}:end -->`;
  const i = text.indexOf(`<!-- ${tag}:begin`);
  const j = text.indexOf(end);
  if (i >= 0 && j > i) text = text.slice(0, i) + section + text.slice(j + end.length);
  else text = text.replace(/\s*$/, '\n\n') + section + '\n';
  writeFileSync(path, text);
  const prettier = await import('prettier');
  const json = await prettier.format(JSON.stringify(jsonOut), { parser: 'json' });
  writeFileSync(jsonPath, json);
}

/* ------------------------------------------------------------------------------------------------ *
 *  main thread
 * ------------------------------------------------------------------------------------------------ */
async function mainThread(): Promise<void> {
  const args = process.argv.slice(2);
  const opt = (k: string, d: string): string =>
    (args.find((a) => a.startsWith(`--${k}=`)) ?? `--${k}=${d}`).split('=').slice(1).join('=');
  const flag = (k: string): boolean => args.includes(`--${k}`);
  const { IMPLEMENTED_TITANS } = await import('@/titans');
  const level = +opt('level', '3');
  const la = +opt('la', String(level)) as Difficulty;
  const lb = +opt('lb', String(level)) as Difficulty;
  const nTarget = +opt('n', '100');
  const seed0 = +opt('seed', '1000');
  const workers = Math.max(1, +opt('workers', String(Math.min(4, availableParallelism()))));
  const timeoutMs = +opt('timeout', '240') * 1000;
  const titans = (opt('titans', '') ? opt('titans', '').split(',') : [...IMPLEMENTED_TITANS]) as TitanId[];
  const mirrors = !flag('no-mirror');

  mkdirSync('.scratch/balance', { recursive: true });
  const store = flag('ladder')
    ? `.scratch/balance/ladder-s${seed0}.json`
    : `.scratch/balance/results-L${la}v${lb}-s${seed0}.json`;
  let results: Result[] = [];
  if (!flag('fresh') && existsSync(store)) {
    try {
      results = JSON.parse(readFileSync(store, 'utf8')) as Result[];
    } catch {
      results = [];
    }
  }
  const done = new Set(results.map((r) => r.key));
  const ladder = flag('ladder');
  const specs: { a: TitanId; b: TitanId; la: Difficulty; lb: Difficulty }[] = [];
  if (ladder) {
    const lp = opt('levels', '6v1,6v3,3v1,5v3').split(',');
    for (const t of titans)
      for (const p of lp) {
        const [x, y] = p.split('v').map(Number) as [Difficulty, Difficulty];
        specs.push({ a: t, b: t, la: x, lb: y });
      }
  } else {
    for (let i = 0; i < titans.length; i++)
      for (let j = i; j < titans.length; j++)
        if (i !== j || mirrors) specs.push({ a: titans[i]!, b: titans[j]!, la, lb });
  }
  const queue: Job[] = [];
  for (let k = 0; k < nTarget; k++)
    for (const sp of specs) {
      const key = `${sp.a}|${sp.b}|L${sp.la}v${sp.lb}|${seed0 + k}`;
      if (done.has(key)) continue;
      queue.push({ key, ...sp, seed: seed0 + k, swapped: k % 2 === 1, index: k });
    }
  const total = specs.length * nTarget;
  console.log(
    `balance${ladder ? ' --ladder' : ''}: ${titans.length} titans, ${specs.length} matchups, ${nTarget} fights each` +
      `${ladder ? '' : ` at L${la}${la === lb ? '' : ` v L${lb}`}`}: ${results.length} stored, ${queue.length} to play on ${workers} workers`,
  );
  const persist = (): void => writeFileSync(store, JSON.stringify(results));
  const emit = async (): Promise<void> => {
    if (flag('no-docs')) return;
    if (ladder) {
      await writeDocs(
        renderLadder(specs, results, seed0, nTarget),
        { seed: seed0, target: nTarget, titans, generatedFrom: store, results },
        'balance-ladder',
        'docs/balance-ladder.json',
      );
      return;
    }
    await writeDocs(render(titans, results, la, lb, seed0, nTarget), {
      level: [la, lb],
      seed: seed0,
      target: nTarget,
      titans,
      generatedFrom: store,
      results,
    });
  };
  if (flag('report')) {
    await emit();
    console.log(`report written from ${results.length} stored fights`);
    return;
  }

  const t0 = performance.now();
  let finished = 0;
  let failed = 0;
  let lastWrite = 0;
  let replacements = 0;
  await new Promise<void>((resolve) => {
    if (queue.length === 0) {
      resolve();
      return;
    }
    let active = 0;
    const spawn = (): void => {
      const w = new Worker(SELF, { workerData: { role: 'worker' }, execArgv: process.execArgv });
      let job: Job | null = null;
      let timer: NodeJS.Timeout | null = null;
      const next = (): void => {
        if (timer) clearTimeout(timer);
        job = queue.shift() ?? null;
        if (!job) {
          active--;
          void w.terminate();
          if (active === 0) resolve();
          return;
        }
        const j = job;
        timer = setTimeout(() => fail(`timeout after ${timeoutMs / 1000} s`), timeoutMs);
        w.postMessage(j);
      };
      const record = (r: Result): void => {
        results.push(r);
        finished++;
        if (r.error) failed++;
        const now = performance.now();
        if (now - lastWrite > 10000) {
          lastWrite = now;
          persist();
          const rate = finished / ((now - t0) / 1000);
          const eta = (queue.length + active) / Math.max(1e-6, rate);
          console.log(
            `  ${results.length}/${total} done (${finished} this run, ${failed} failed), ${rate.toFixed(2)} fights/s, eta ${(eta / 60).toFixed(1)} min`,
          );
        }
      };
      const fail = (why: string): void => {
        const j = job;
        job = null;
        if (timer) clearTimeout(timer);
        void w.terminate();
        if (j)
          record({
            key: j.key,
            a: j.a,
            b: j.b,
            index: j.index,
            swapped: j.swapped,
            winner: 'draw',
            roundsA: 0,
            roundsB: 0,
            rounds: [],
            timeouts: 0,
            ticks: 0,
            error: why,
            wallMs: 0,
          });
        replacements++;
        if (replacements > 40 + total / 10) {
          persist();
          console.log('balance: too many worker failures, giving up (partial results kept)');
          process.exit(1);
        }
        console.log(`  worker replaced (${why}${j ? ` at ${j.key}` : ''})`);
        active--;
        if (queue.length > 0) {
          active++;
          spawn();
        } else if (active === 0) resolve();
      };
      w.on('message', (m: Result | { ready: true }) => {
        if ('ready' in m) {
          next();
          return;
        }
        record(m);
        next();
      });
      w.on('error', (e) => fail(`worker error: ${e.message}`));
      w.on('exit', (code) => {
        if (job && code !== 0) fail(`worker exit ${code}`);
      });
    };
    for (let i = 0; i < workers; i++) {
      active++;
      spawn();
    }
  });
  persist();
  await emit();
  console.log(
    `balance: finished ${finished} fights in ${((performance.now() - t0) / 60000).toFixed(1)} min (${failed} failed). ` +
      `results ${store}${flag('no-docs') ? '' : '; docs/BALANCE.md and docs/balance-results.json updated'}`,
  );
}

if (isMainThread) {
  if (process.argv[1] && fileURLToPath(import.meta.url) === process.argv[1]) void mainThread();
} else if ((workerData as { role?: string } | null)?.role === 'worker') {
  void workerMain();
}
